#!/usr/bin/python
# -*- coding: utf-8 -*-

platforms = {
  1: 'android',
  2: 'ios',
  3: 'windows',
}

categories = {
  1: u"Games",
  2: u"Social",
  3: u"Entertainment",
  4: u"Multimedia",
  5: u"Sports",
  6: u"Books & Reference",
  7: u"News & Weather",
  8: u"Health",
  9: u"Shopping & Lifestyle",
  10: u"Travel",
  11: u"Finance",
  12: u"Productivity",
  13: u"Tools",
  14: u"Business",
  15: u"Education",
  16: u"Public Government",
}

android = {
  u"Casual": 1,
  u"Photography": 4,
  u"Communication": 2,
  u"Lifestyle": 9,
  u"Strategy": 1,
  u"Shopping": 9,
  u"Word": 1,
  u"News & Magazines": 7,
  u"Productivity": 12,
  u"Health & Fitness": 8,
  u"Role Playing": 1,
  u"Books & Reference": 6,
  u"Medical": 8,
  u"Social": 2,
  u"Transportation": 10,
  u"Casino": 1,
  u"Music": 1,
  u"Comics": 6,
  u"Puzzle": 1,
  u"Weather": 7,
  u"Travel & Local": 10,
  u"Media & Video": 4,
  u"Libraries & Demo": 13,
  u"Tools": 13,
  u"Finance": 11,
  u"Racing": 1,
  u"Card": 1,
  u"Business": 14,
  u"Board": 1,
  u"Educational": 1,
  u"Trivia": 1,
  u"Action": 1,
  u"Education": 15,
  u"Personalization": 13,
  u"Live Wallpaper": 13,
  u"Adventure": 1,
  u"Widgets": 13,
  u"Family": 1,
  u"Arcade": 1,
  u"Music & Audio": 4,
  u"Entertainment": 3,
  u"Sports": 5,
  u"Simulation": 1,
  u"Game Sports": 1,
}

windows = {
  u"Productivity": 12,
  u"Παραγωγικότητα": 12,
  u"Μουσική και βίντεο": 4,
  u"Αγορές": 9,
  u"Χρηματοοικονομικά": 11,
  u"Lifestyle": 9,
  u"Επιχειρήσεις": 14,
  u"Φωτογραφία": 4,
  u"Κοινωνικά δίκτυα": 2,
  u"Εργαλεία": 13,
  u"Εκπαίδευση": 15,
  u"News & Weather": 7,
  u"Δημόσια διοίκηση": 16,
  u"Ειδήσεις και καιρός": 7,
  u"Entertainment": 3,
  u"Ψυχαγωγία": 3,
  u"Games": 1,
  u"Ταξίδια": 10,
  u"Αθλητικά": 5,
  u"Ασφάλεια": 13,
  u"Φαγητό & εστίαση": 9,
  u"Βιβλία και αναφορά": 6,
  u"Παιχνίδια": 1,
  u"Υγεία και ευεξία": 8,
}

ios = {
  u"Productivity": 12,
  u"Photo & Video": 4,
  u"Entertainment": 3,
  u"Travel": 10,
  u"Sports": 5,
  u"Food & Drink": 9,
  u"Book": 6,
  u"Music": 4,
  u"Health & Fitness": 8,
  u"Finance": 11,
  u"Business": 14,
  u"Social Networking": 2,
  u"Utilities": 13,
  u"News": 7,
  u"Lifestyle": 9,
  u"Medical": 8,
  u"Games": 1,
  u"Catalogs": 9,
  u"Navigation": 10,
  u"Reference": 6,
  u"Weather": 7,
  u"Education": 15,
}
